#!/usr/bin/env python3

# Build script with pyinstaller

import PyInstaller.__main__
from sys import platform
import os

if platform != "win32":
    print("Building is supported only for Windows. Use 'install' for installation in Linux (or the AUR for ArchLinux).")
    exit()

PyInstaller.__main__.run([
    'temp-logger',
    '--console',
    '--distpath','bin',
    '--workpath','.build',
    '--noconfirm','--onefile'
])
